# Conformance domain: `mkContractPackage`, its home-manager producer adapter
# `mkContractPackageForHome`, and `bindContractPackage`.
#
# mkContractPackage is proven by an execution proof (the derivation builds and has the right
# content); the adapter by an eval-level equivalence proof (a synthetic home forwards to the SAME
# content-addressed store path). bindContractPackage is proven at eval level, reading a STATIC
# fixture rather than evaluating a home — so it proves the manifest→account kernel only; that a
# real home builds through the contract is proven where home-manager lives (`examples/users`,
# whose `checks = packages` build every real home). The fixture is a plain repo path (no
# derivation, no IFD) — a realized store path, exactly as a production contractPackage is a
# pinned/realized flake input.
#
# The manifest schema owner is proven here too: a write→read ROUND-TRIP, a refusal of a manifest
# written at a version this contract does not read, and an equivalence check that each repo
# fixture's JSON is byte-identical to `writeManifest`'s output — so the fixtures are GENERATED by
# the schema owner and cannot silently drift from it, while staying realized repo paths.
{
  lib,
  pkgs,
  toolkit,
  mkContractPackage,
  mkContractPackageForHome,
  bindContractPackage,
  writeManifest,
  readManifest,
  manifestFileName,
  manifestVersion,
}:
let
  inherit (toolkit) eval referenceIdentity;

  # --- mkContractPackage execution proof ---
  # A minimal activationPackage stub: just an `activate` script at the root.
  activationStub = pkgs.runCommand "mkContractPackage-activation-stub" { } ''
    mkdir -p $out
    printf '#!/bin/sh\necho activated\n' > $out/activate
    chmod +x $out/activate
  '';

  # The primitives, single-sourced so the direct call and the adapter's synthetic home draw from
  # the SAME values — the equivalence proof below then attests the adapter reads the right
  # attribute PATHS, not that two hand-typed literal sets happen to coincide.
  primitives = {
    packages = [ pkgs.hello ];
    username = "testuser";
  };

  # Build a real contractPackage from known inputs. The manifest is constructed at eval time
  # (builtins.toFile, no IFD); the derivation just copies both files.
  contractPackage = mkContractPackage {
    inherit pkgs;
    activationPackage = activationStub;
    inherit (primitives) packages username;
    mode = "cli";
  };

  # --- mkContractPackageForHome adapter proof ---
  # The adapter only READS primitives off an already-evaluated home (no home-manager import). A
  # synthetic home whose attribute paths mirror a `homeManagerConfiguration` result stands in for a
  # real one, carrying the SAME primitives at the paths the adapter reads.
  syntheticHome = {
    activationPackage = activationStub;
    config.home = {
      inherit (primitives) packages username;
    };
  };

  # The adapter forwards those primitives into `mkContractPackage`. With identical inputs the
  # derivation is content-addressed to the SAME store path as the direct call above — an
  # eval-level equivalence proof that the adapter extracts every attribute correctly and adds
  # nothing of its own.
  contractPackageFromHome = mkContractPackageForHome {
    inherit pkgs;
    home = syntheticHome;
    mode = "cli";
  };

  # A SECOND mode through the same adapter. Every artifact belongs to a mode (there is no default
  # to fall back on), so what is left to prove is that the adapter carries the one it is handed.
  # Paired with the non-vacuity check below (the two modes yield different artifacts), this proves
  # the adapter neither drops the mode nor substitutes one — at the seam that freezes it.
  contractPackageFromHomeMode = mkContractPackageForHome {
    inherit pkgs;
    home = syntheticHome;
    mode = "gui";
  };
  contractPackageMode = mkContractPackage {
    inherit pkgs;
    activationPackage = activationStub;
    inherit (primitives) packages username;
    mode = "gui";
  };

  # Execution proof: build the derivation and verify its content.
  contentCheck =
    pkgs.runCommand "contract-package-content-check" { nativeBuildInputs = [ pkgs.jq ]; }
      ''
        echo "--- activate ---"
        test -x ${contractPackage}/activate

        echo "--- ${manifestFileName} ---"
        manifest=${contractPackage}/${manifestFileName}
        jq . "$manifest"

        jq -e '.version == ${toString manifestVersion}' "$manifest"
        jq -e '.username == "testuser"'                 "$manifest"
        jq -e '.mode == "cli"'                          "$manifest"
        jq -e '.packages | contains(["hello"])'         "$manifest"

        touch $out
      '';

  # --- bindContractPackage eval proof ---
  # A plain repo-path fixture (no derivation build, no IFD) so the eval assertions stay pure.
  cliFixture = ./fixtures/reference-contract-package;
  guiFixture = ./fixtures/reference-contract-package-gui;

  # `runs` is required on every bind, so these two hand the kernel a host running both modes. What
  # differs between them is the GRANT — which is the point of the pair, and exactly the
  # independence the design asserts: what a host RUNS and what it CONFERS are two questions.
  hostRunsBoth = [
    "cli"
    "gui"
  ];
  boundGranted = eval [
    (bindContractPackage {
      contractPackage = cliFixture;
      identity = referenceIdentity;
      runs = hostRunsBoth;
      grants = {
        sudo = true;
      };
    })
  ];
  boundNone = eval [
    (bindContractPackage {
      contractPackage = cliFixture;
      identity = referenceIdentity;
      runs = hostRunsBoth;
      grants = { };
    })
  ];

  # --- the MODE coupling guard ---
  # The gui fixture's manifest FREEZES `mode = "gui"` — the field the guard checks.
  # `bindContractPackage` asserts the frozen mode is one the host RUNS:
  #   - ACCEPT when the host runs gui;
  #   - REJECT (hard eval error, caught by tryEval) when it does not — a home built for a graphical
  #     session must never be activated on a machine that cannot run one.
  # This is the INTERNAL path, which is the whole point of the guard: `bindContractUser`'s
  # selection satisfies it by construction, so the only way to reach it is to call the kernel
  # directly.
  bindFixtureOn =
    package: runs:
    builtins.tryEval (
      (eval [
        (bindContractPackage {
          contractPackage = package;
          identity = referenceIdentity;
          inherit runs;
          grants = {
            gui = true;
          };
        })
      ]).users.users.ada.isNormalUser
    );
  guardAccept = bindFixtureOn guiFixture hostRunsBoth;
  guardReject = bindFixtureOn guiFixture [ "cli" ];
  # The control: the SAME host that rejects the gui fixture accepts the cli one, so the refusal is
  # about the frozen mode rather than about the host or the fixture path.
  guardControl = bindFixtureOn cliFixture [ "cli" ];

  # --- manifest schema owner: round-trip, version refusal, fixture generation ---
  # The fields each repo fixture is GENERATED from. Single-sourced here so the equivalence check
  # below attests the committed JSON is byte-identical to `writeManifest`'s output — the fixtures
  # are produced by the schema owner, not a hand-typed blob that could drift from it.
  cliFields = {
    username = "ada";
    packages = [ "hello" ];
    mode = "cli";
  };
  guiFields = cliFields // {
    mode = "gui";
  };
  # Round-trip through the two schema functions: read(write(fields)) recovers the original fields
  # (write stamps `version`, which readManifest surfaces — so compare with version dropped).
  roundTrip = readManifest (writeManifest guiFields);
  # A manifest written at a version this contract does not read. There is no compatibility read:
  # the producer and the host are pinned to different contract revisions, and guessing at the shape
  # would put a user's account together out of fields nobody agreed on.
  wrongVersion = builtins.tryEval (
    readManifest (writeManifest (guiFields // { version = manifestVersion - 1; }))
  );
  # The committed fixture JSON vs. writeManifest's output for the same fields — byte equality
  # proves the fixture is generated, not hand-maintained (a plain readFile of realized paths).
  fixtureIsGenerated =
    package: fields:
    builtins.readFile (package + "/${manifestFileName}") == builtins.readFile (writeManifest fields);
in
{
  assertions = [
    # mkContractPackage (execution proof lives in drvs; the eval assertion checks the drv exists)
    {
      name = "mkContractPackage: produces a derivation (content verified by execution proof)";
      ok = contractPackage ? outPath;
    }

    # mkContractPackageForHome: the home adapter is exactly the disassembly mkContractPackage
    # expects — same content-addressed store path as the direct call from equal primitives.
    {
      name = "mkContractPackageForHome: reads home primitives into an identical contractPackage";
      ok = contractPackageFromHome.outPath == contractPackage.outPath;
    }
    {
      name = "mkContractPackageForHome: forwards the mode identically to the direct call";
      ok = contractPackageFromHomeMode.outPath == contractPackageMode.outPath;
    }
    {
      # …and non-vacuously: a mode actually changes the artifact, so the check above is proving
      # forwarding, not that the mode is inert.
      name = "mkContractPackageForHome: a mode changes the artifact (forwarding is real)";
      ok = contractPackageFromHomeMode.outPath != contractPackageFromHome.outPath;
    }

    # bindContractPackage: the account, and the whole of it
    {
      name = "bindContractPackage: the account materializes from identity";
      ok =
        boundGranted.users.users.ada.isNormalUser
        && boundGranted.users.users.ada.description == "Ada Reference";
    }
    {
      # The kernel writes the GRANT onto the account, verbatim and complete. There is nothing to
      # bridge and nothing to derive: a feature has no parameters, so what the host afforded is the
      # whole of what the account holds.
      name = "bindContractPackage: the grant reaches the account, and only what was afforded";
      ok =
        let
          g = boundGranted.contract.users.ada.granted;
        in
        g.sudo && !g.containers && lib.all (v: !v) (lib.attrValues boundNone.contract.users.ada.granted);
    }
    {
      # …and the MODE the manifest froze reaches it too, because the account needs it: a session
      # shape's groups ride the mode. Note what this kernel does NOT decide — the display surface,
      # which follows the machine's `contract.modes` and is nobody's grant. Neither of these two
      # binds turns one on, and both are perfectly ordinary.
      name = "bindContractPackage: the frozen mode reaches the account; no bind turns on a display";
      ok =
        boundGranted.contract.users.ada.mode == "cli"
        && !boundGranted.contract.display.enabled
        && !boundNone.contract.display.enabled;
    }
    {
      name = "bindContractPackage: activation service is registered in systemd";
      ok = boundGranted.systemd.services ? "contract-activate-ada";
    }
    {
      name = "bindContractPackage: no profile replacement when allowedPrograms is empty (default)";
      ok =
        let
          svcConfig = boundGranted.systemd.services."contract-activate-ada".serviceConfig or { };
        in
        !(svcConfig ? ExecStartPost);
    }

    # the mode coupling guard: accept when the host runs the frozen mode, reject when it does not
    {
      name = "coupling guard: manifest mode=gui, host runs [cli, gui] ⇒ accept (binds)";
      ok = guardAccept.success && guardAccept.value;
    }
    {
      name = "coupling guard: manifest mode=gui, host runs [cli] ⇒ reject (hard eval error)";
      ok = !guardReject.success;
    }
    {
      # The control, on the very host whose `runs = [ cli ]` rejected the gui fixture: same host,
      # same grants, only the frozen mode differs. Without it, "the guard rejects" could hold for a
      # reason that has nothing to do with the mode.
      name = "coupling guard: the SAME [cli] host accepts a manifest frozen at cli (the control)";
      ok = guardControl.success && guardControl.value;
    }

    # manifest schema owner
    {
      name = "manifest round-trip: readManifest (writeManifest fields) recovers the fields";
      ok = builtins.removeAttrs roundTrip [ "version" ] == guiFields;
    }
    {
      name = "manifest round-trip: writeManifest stamps the current version";
      ok = roundTrip.version == manifestVersion;
    }
    {
      # No compatibility read, deliberately: a manifest this contract does not recognise means the
      # producer and the host are on different revisions, and a shape guessed at would assemble an
      # account out of fields nobody agreed on.
      name = "manifest version: a manifest written at another version is a hard, named error";
      ok = !wrongVersion.success;
    }
    {
      name = "fixture generation: reference-contract-package is byte-identical to writeManifest output";
      ok = fixtureIsGenerated cliFixture cliFields;
    }
    {
      name = "fixture generation: reference-contract-package-gui is byte-identical to writeManifest output";
      ok = fixtureIsGenerated guiFixture guiFields;
    }
  ];

  drvs = {
    "contract-package-content-check" = contentCheck;
  };
}
