# Conformance domain: mkContractPackage (ADR-0016, issue #14), its home-manager producer
# adapter mkContractPackageForHome (issue #23), and bindContractPackage (ADR-0016, issue #16).
# mkContractPackage is proven by an execution proof (the derivation builds and has correct
# content); mkContractPackageForHome by an eval-level equivalence proof (a synthetic home
# forwards to the SAME content-addressed store path). bindContractPackage is proven at eval
# level: the same gui surface and account the traceUser inspector resolves emerges from reading a
# pre-built contract-requests.json fixture — same `mkUserAccount` + `bridgeRequests` kernel,
# different data source. It reads a STATIC fixture and never evaluates a home, so it proves the
# manifest→bridge kernel only; that a real non-contract-pure home builds through the contract is
# proven where home-manager lives — `examples/users`, whose `checks = packages` build every real
# home (ADR-0004, package-free). The
# fixture is a plain repo path (no derivation, no IFD) — a realized store path, exactly as a
# production contractPackage is a pinned/realized flake input.
#
# The manifest schema owner (the `manifest` module, issue #27) is proven here too: a write->read
# ROUND-TRIP (`readManifest (writeManifest fields)` yields the original account fields, incl. a
# pre-v3 manifest read with the `mode` field absent), and an equivalence check that each repo
# fixture's JSON is byte-identical to `writeManifest`'s output — so the fixtures are GENERATED by
# the schema owner and cannot silently drift from it, while staying realized repo paths (no IFD).
{
  pkgs,
  toolkit,
  mkContractPackage,
  mkContractPackageForHome,
  bindContractPackage,
  writeManifest,
  readManifest,
  manifestFileName,
  greeterGrants,
}:
let
  inherit (toolkit) eval referenceIdentity;

  # --- mkContractPackage execution proof (issue #14) ---
  # A minimal activationPackage stub: just an `activate` script at the root.
  activationStub = pkgs.runCommand "mkContractPackage-activation-stub" { } ''
    mkdir -p $out
    printf '#!/bin/sh\necho activated\n' > $out/activate
    chmod +x $out/activate
  '';

  # The four primitives, single-sourced so the direct call and the adapter's synthetic home draw
  # from the SAME values — the equivalence proof below then attests the adapter reads the right
  # attribute PATHS, not that two hand-typed literal sets happen to coincide.
  primitives = {
    requests = {
      gui.desktop = "plasma";
    };
    packages = [ pkgs.hello ];
    username = "testuser";
  };

  # Build a real contractPackage from known inputs. The manifest is constructed at eval time
  # (builtins.toFile, no IFD); the derivation just copies both files.
  contractPackage = mkContractPackage {
    inherit pkgs;
    activationPackage = activationStub;
    inherit (primitives) requests packages username;
  };

  # --- mkContractPackageForHome adapter proof (issue #23) ---
  # The home-manager producer adapter only READS the four primitives off an already-evaluated
  # home (no home-manager import — ADR-0004). A synthetic home whose attribute paths mirror a
  # `homeManagerConfiguration` result stands in for a real one: proving the adapter is exactly
  # the disassembly `mkContractPackage` expects needs no home-manager in the loop. It carries the
  # SAME primitives, placed at the home attribute paths the adapter reads.
  syntheticHome = {
    activationPackage = activationStub;
    config = {
      contract.requests = primitives.requests;
      home = {
        inherit (primitives) packages username;
      };
    };
  };

  # The adapter forwards those primitives into `mkContractPackage`. With identical inputs the
  # derivation is content-addressed to the SAME store path as the direct call above — an
  # eval-level equivalence proof that the adapter extracts every attribute correctly and adds
  # nothing of its own (same name, same activate, same manifest).
  contractPackageFromHome = mkContractPackageForHome {
    inherit pkgs;
    home = syntheticHome;
  };

  # The MODE forwards through the adapter too (not just the default `null`). A home assembled for
  # a mode must match the direct call fed the same mode — so the frozen mode (the ADR-0016 coupling
  # guard as ADR-0032 §8 restates it) survives the adapter. Paired with a non-vacuity check below
  # (a mode CHANGES the artifact), this proves the adapter neither drops nor mangles it.
  contractPackageFromHomeMode = mkContractPackageForHome {
    inherit pkgs;
    home = syntheticHome;
    mode = "gui";
  };
  contractPackageMode = mkContractPackage {
    inherit pkgs;
    activationPackage = activationStub;
    inherit (primitives) requests packages username;
    mode = "gui";
  };

  # Execution proof: build the derivation and verify its content.
  contentCheck =
    pkgs.runCommand "contract-package-content-check" { nativeBuildInputs = [ pkgs.jq ]; }
      ''
        echo "--- activate ---"
        test -x ${contractPackage}/activate

        echo "--- contract-requests.json ---"
        manifest=${contractPackage}/contract-requests.json
        jq . "$manifest"

        jq -e '.version == 3'              "$manifest"
        jq -e '.username == "testuser"'    "$manifest"
        jq -e '.packages | contains(["hello"])' "$manifest"
        jq -e '.requests.gui.desktop == "plasma"' "$manifest"

        touch $out
      '';

  # --- bindContractPackage eval proof (issue #16) ---
  # Use a plain repo-path fixture (no derivation build needed, no IFD) so the eval assertions
  # stay pure. The fixture mirrors the reference user ada's request: gui.desktop = "plasma". Its
  # JSON is `writeManifest`'s output (a v1 manifest), proven byte-identical below (issue #27).
  fixturePackage = ./fixtures/reference-contract-package;

  boundRuntime = eval [
    (bindContractPackage {
      contractPackage = fixturePackage;
      identity = referenceIdentity;
      grants = greeterGrants;
    })
  ];
  boundNone = eval [
    (bindContractPackage {
      contractPackage = fixturePackage;
      identity = referenceIdentity;
      grants = { };
    })
  ];

  # --- the MODE coupling guard (ADR-0016's guard as ADR-0032 §8 restates it) ---
  # A v3 fixture whose manifest FREEZES `mode = "gui"` — the field the guard checks. A plain repo
  # path (no derivation, no IFD) so accept/reject stay eval-level. `bindContractPackage` asserts
  # the frozen mode is one the host RUNS:
  #   - ACCEPT when the host runs gui;
  #   - REJECT (hard eval error, caught by tryEval) when it does not — a home built for a graphical
  #     session must never be activated on a machine that cannot run one.
  # This is the INTERNAL path, which is the whole point of the guard: `bindContractUser`'s selection
  # satisfies it by construction, so the only way to reach it is to call the kernel directly.
  guiFixture = ./fixtures/reference-contract-package-gui;
  bindGuiFixtureOn =
    runs:
    builtins.tryEval (
      (eval [
        (bindContractPackage {
          contractPackage = guiFixture;
          identity = referenceIdentity;
          inherit runs;
          grants = {
            gui = true;
          };
        })
      ]).users.users.ada.isNormalUser
    );
  guardAccept = bindGuiFixtureOn [
    "cli"
    "gui"
  ];
  guardReject = bindGuiFixtureOn [ "cli" ];
  # …and the SKIP: a caller with no host in sight (`runs` unpassed) has nothing to check against,
  # which is how the kernel stays a pure function of what it is handed.
  guardSkipped = builtins.tryEval (
    (eval [
      (bindContractPackage {
        contractPackage = guiFixture;
        identity = referenceIdentity;
        grants = {
          gui = true;
        };
      })
    ]).users.users.ada.isNormalUser
  );

  # --- manifest schema owner: round-trip + fixture generation (issue #27) ---
  # The account fields each repo fixture is GENERATED from. Single-sourced here so the equivalence
  # check below attests the committed JSON is byte-identical to `writeManifest`'s output — the
  # fixtures are produced by the schema owner, not a hand-typed blob that could drift from it.
  # `referenceFields` is v1 (no `mode`, exercising the backward-compat read); `guiFields` is v3.
  referenceFields = {
    version = 1;
    username = "ada";
    requests = {
      gui.desktop = "plasma";
    };
    packages = [ "hello" ];
  };
  guiFields = {
    username = "ada";
    requests = {
      gui.desktop = "plasma";
    };
    packages = [ "hello" ];
    mode = "gui";
  };
  # Round-trip through the two schema functions: read(write(fields)) recovers the original account
  # fields (write stamps `version`, which readManifest surfaces — so compare with version dropped).
  guiRoundTrip = readManifest (writeManifest guiFields);
  # Backward compat: a v1 manifest (written before `mode` existed) reads back with `mode = null`.
  referenceRoundTrip = readManifest (writeManifest referenceFields);
  # The committed fixture JSON vs. writeManifest's output for the same fields — byte equality proves
  # the fixture is generated, not hand-maintained (a plain readFile of realized paths, no IFD).
  fixtureIsGenerated =
    package: fields:
    builtins.readFile (package + "/${manifestFileName}") == builtins.readFile (writeManifest fields);
in
{
  assertions = [
    # mkContractPackage (execution proof lives in drvs; the eval assertion checks the drv exists)
    {
      name = "mkContractPackage: produces a derivation (content verified by execution proof)";
      ok = contractPackage ? outPath;
    }

    # mkContractPackageForHome: the home adapter is exactly the disassembly mkContractPackage
    # expects — same content-addressed store path as the direct call from equal primitives.
    {
      name = "mkContractPackageForHome: reads home primitives into an identical contractPackage";
      ok = contractPackageFromHome.outPath == contractPackage.outPath;
    }

    # mkContractPackageForHome: the mode forwards identically — the frozen mode survives.
    {
      name = "mkContractPackageForHome: forwards the mode identically to the direct call";
      ok = contractPackageFromHomeMode.outPath == contractPackageMode.outPath;
    }

    # ...and non-vacuously: a mode actually changes the artifact, so the check above is proving
    # forwarding, not that the mode is inert.
    {
      name = "mkContractPackageForHome: a mode changes the artifact (forwarding is real)";
      ok = contractPackageFromHomeMode.outPath != contractPackageFromHome.outPath;
    }

    # bindContractPackage: account materializes from identity
    {
      name = "bindContractPackage: the account materializes from identity";
      ok =
        boundRuntime.users.users.ada.isNormalUser
        && boundRuntime.users.users.ada.description == "Ada Reference";
    }

    # bindContractPackage: granted request enables the gui surface (parity with the traceUser kernel)
    {
      name = "bindContractPackage: a granted gui request enables the display surface";
      ok = boundRuntime.custom.gui.surface.enabled;
    }

    # bindContractPackage: ungranted request is inert
    {
      name = "bindContractPackage: an ungranted request is inert (no surface)";
      ok = !boundNone.custom.gui.surface.enabled;
    }

    # bindContractPackage: systemd activation service is registered
    {
      name = "bindContractPackage: activation service is registered in systemd";
      ok = boundRuntime.systemd.services ? "contract-activate-ada";
    }

    # bindContractPackage: no package policy profile replacement when allowedPrograms is empty
    {
      name = "bindContractPackage: no profile replacement when allowedPrograms is empty (default)";
      ok =
        let
          svcConfig = boundRuntime.systemd.services."contract-activate-ada".serviceConfig or { };
        in
        !(svcConfig ? ExecStartPost);
    }

    # the mode coupling guard: accept when the host runs the frozen mode, reject when it does not
    {
      name = "coupling guard: manifest mode=gui, host runs [cli, gui] ⇒ accept (binds)";
      ok = guardAccept.success && guardAccept.value;
    }
    {
      name = "coupling guard: manifest mode=gui, host runs [cli] ⇒ reject (hard eval error)";
      ok = !guardReject.success;
    }
    {
      name = "coupling guard: no `runs` handed ⇒ nothing to check against (skipped, not fired)";
      ok = guardSkipped.success && guardSkipped.value;
    }

    # manifest schema owner: write->read round-trip recovers the original account fields
    {
      name = "manifest round-trip: readManifest (writeManifest fields) recovers the account fields";
      ok = builtins.removeAttrs guiRoundTrip [ "version" ] == guiFields;
    }
    {
      name = "manifest round-trip: writeManifest stamps the current version (3)";
      ok = guiRoundTrip.version == 3;
    }
    # backward compat: a pre-v3 manifest (field absent) reads back with mode = null
    {
      name = "manifest compat: a v1 manifest reads back with mode = null (pre-v3 compat)";
      ok =
        referenceRoundTrip.version == 1
        && referenceRoundTrip.mode == null
        && builtins.removeAttrs referenceRoundTrip [ "mode" ] == referenceFields;
    }
    # fixtures are generated by writeManifest (byte-identical), not hand-maintained JSON
    {
      name = "fixture generation: reference-contract-package is byte-identical to writeManifest output";
      ok = fixtureIsGenerated fixturePackage referenceFields;
    }
    {
      name = "fixture generation: reference-contract-package-gui is byte-identical to writeManifest output";
      ok = fixtureIsGenerated guiFixture guiFields;
    }
  ];

  drvs = {
    "contract-package-content-check" = contentCheck;
  };
}
